### ISSUE TITLE
Works the first time then stops

### ISSUE THREAD

**Issue by mhamilt** [rankinjonathan/RNLI-launcher#1]
>So far it works the first time, then stops. I wonder if it is something to do with memory, but I really don’t know. I am using the UxU8 library because there there doesn’t need to be a buffer in the micro controller, and I am only outputting text. 

It depends if it is continuing to print to serial or if the entire thing just seems to freeze.

Here are some things I've spotted:

does this need to be in the main loop (probably not)?

https://github.com/rankinjonathan/RNLI-launcher/blob/da930d58cf9fa4164239323a27ce16c19acb9379/RNLI-launcher.ino#L138

***

Keep a close eye on `X` and make sure the logic of all this works

https://github.com/rankinjonathan/RNLI-launcher/blob/da930d58cf9fa4164239323a27ce16c19acb9379/RNLI-launcher.ino#L127

https://github.com/rankinjonathan/RNLI-launcher/blob/da930d58cf9fa4164239323a27ce16c19acb9379/RNLI-launcher.ino#L157

https://github.com/rankinjonathan/RNLI-launcher/blob/da930d58cf9fa4164239323a27ce16c19acb9379/RNLI-launcher.ino#L167

***

Debugging:

- [x] Double check the feather Wifi firmware and make sure that is up to date
- [x] Remove the display (physically and in code) and simply print to Serial

**Comment by mhamilt** [comment]
Think about maybe adding in a delay or only printing information if it has changed since the last print

**Comment by rankinjonathan** [comment]
> does this need to be in the main loop (probably not)?
> 
> https://github.com/rankinjonathan/RNLI-launcher/blob/da930d58cf9fa4164239323a27ce16c19acb9379/RNLI-launcher.ino#L138

When I move this outside of the main loop, to the setup loop nothing shows on the display.

If I remove the display in code it works with serial print.
If I remove the display physically but keep the code the same, it also works

**Comment by mhamilt** [comment]
Move the  `u8x8.begin();` to `setup()` 

You shouldn't need to start it more than once

**Comment by rankinjonathan** [comment]
> Move the `u8x8.begin();` to `setup()`
> 
> You shouldn't need to start it more than once

Yes, when I do that nothing shows on the screen. Does that give any clues as to why it is not working?

**Comment by mhamilt** [comment]
The examples all suggest `.begin()` should be in the setup. If for some reason that isn't working you should take a few steps back to a simple example to double check.

**Comment by rankinjonathan** [comment]
> The examples all suggest `.begin()` should be in the setup. If for some reason that isn't working you should take a few steps back to a simple example to double check.

Yes I have/have had a simple version working using all of the same commands

`#include <Arduino.h>
#include <U8x8lib.h>

#ifdef U8X8_HAVE_HW_SPI
#include <SPI.h>
#endif
#ifdef U8X8_HAVE_HW_I2C
#include <Wire.h>
#endif


String tweet = "";


U8X8_SSD1322_NHD_256X64_4W_SW_SPI u8x8(/* clock=*/ 24, /* data=*/ 23, /* cs=*/ 10, /* dc=*/ 9, /* reset=*/ 5);

void setup(void) {


  Serial.begin(9600);				// Start reading from Serial communication interface

  u8x8.begin();
  u8x8.setFont(u8x8_font_chroma48medium8_r);	// set the font for the terminal window
}

void loop(void) {
  tweet = "Jonathan";
  Serial.print("TEST POINT 1");
  Serial.println("\n");
  u8x8.clear();
  u8x8.setCursor(0, 0);
  u8x8.print(tweet);

  delay(10000);
  tweet = "Clare";
  Serial.print("TEST POINT 2");
  Serial.println("\n");
  u8x8.clear();
  u8x8.setCursor(0, 0);
  u8x8.print(tweet);
  delay(10000);


}`

**Comment by mhamilt** [comment]
Did this work correctly

>```ino
>#include <Arduino.h>
>#include <U8x8lib.h>
>#include <SPI.h>
>
>String tweet = "";
>
>U8X8_SSD1322_NHD_256X64_4W_SW_SPI u8x8(24, 23, 10, 9, 5);
>
>void setup(void) 
>{
>  Serial.begin(9600); // Start reading from Serial communication interface
>
>  u8x8.begin();
>  u8x8.setFont(u8x8_font_chroma48medium8_r); // set the font for the terminal window
>}
>
>void loop(void) 
>{
>  tweet = "Jonathan";
>  Serial.print("TEST POINT 1");
>  Serial.println("\n");
>  u8x8.clear();
>  u8x8.setCursor(0, 0);
>  u8x8.print(tweet);
>
>  delay(10000);
>  tweet = "Clare";
>  Serial.print("TEST POINT 2");
>  Serial.println("\n");
>  u8x8.clear();
>  u8x8.setCursor(0, 0);
>  u8x8.print(tweet);
>  delay(10000);
>}
>```

**Comment by mhamilt** [comment]
Those SPI pins may not be correct

**Comment by rankinjonathan** [comment]
> Did this work correctly
> 
> > ```c++
> > #include <Arduino.h>
> > #include <U8x8lib.h>
> > #include <SPI.h>
> > 
> > String tweet = "";
> > 
> > U8X8_SSD1322_NHD_256X64_4W_SW_SPI u8x8(24, 23, 10, 9, 5);
> > 
> > void setup(void) 
> > {
> >  Serial.begin(9600); // Start reading from Serial communication interface
> > 
> >  u8x8.begin();
> >  u8x8.setFont(u8x8_font_chroma48medium8_r); // set the font for the terminal window
> > }
> > 
> > void loop(void) 
> > {
> >  tweet = "Jonathan";
> >  Serial.print("TEST POINT 1");
> >  Serial.println("\n");
> >  u8x8.clear();
> >  u8x8.setCursor(0, 0);
> >  u8x8.print(tweet);
> > 
> >  delay(10000);
> >  tweet = "Clare";
> >  Serial.print("TEST POINT 2");
> >  Serial.println("\n");
> >  u8x8.clear();
> >  u8x8.setCursor(0, 0);
> >  u8x8.print(tweet);
> >  delay(10000);
> > }
> > ```

This works correctly, I have also tried copying this in at the start of the RNLI launcher loop so that it displays Jonathan and Clare then runs through  the rest of the code. It continues to run but nothing shows on the screen.

` io.run();

  tweet = "Jonathan";
  Serial.print("TEST POINT 1");
  Serial.println("\n");
  u8x8.clear();
  u8x8.setCursor(0, 0);
  u8x8.print(tweet);

  delay(10000);
  tweet = "Clare";
  Serial.print("TEST POINT 2");
  Serial.println("\n");
  u8x8.clear();
  u8x8.setCursor(0, 0);
  u8x8.print(tweet);
  delay(10000);


  timer = millis() - timerOffset;


  //-------------------------- If there is a timer runing and an event happened  --------------------------

  if (X > 0 && contractLength > timer && happened == 1) {
    Serial.println("Donate £1");
    Serial.print("counter =    ");
    Serial.println(X);
    //-------------------------- Do this section if there is a RNLI launch  --------------------------

    Serial.println(tweet);

    Serial.print("TEST POINT 3");
    Serial.println("\n");`

**Comment by mhamilt** [comment]
That timer code looks fine but something feels a little fishy. I'm going to put in a pull request to tidy some bits and pieces up.

It may be worth while re-writing the timing side of things to make it clearer whats going on.

Something in the format `(currentTime - startTime) < contractLength` is a bit clearer, at least for me. 

Double check your timer logic by printing out time left

```ino
Serial.print("Time Left in Contract: ");
Serial.print((contractLength - (currentTime - startTime))/1000);
Serial.println(" seconds");
```

Pull Request: https://github.com/rankinjonathan/RNLI-launcher/pull/2

**Comment by rankinjonathan** [comment]
Ok, I have cleaned up the timer function and serial printed the time to check logic. 

Still all works ok, but still nothing printing to the screen.

**Comment by mhamilt** [comment]
Start with a simplified version of what you have and start adding back in code until it breaks.

Here is a version that should just count down the remaining time.

Next step to this would be

- Print Time remaining on first line
- Print Tweet on second line.

```ino
//-----------------------------------------------------------------
#include <U8x8lib.h>
#include <SPI.h>
#include <Wire.h>
//-----------------------------------------------------------------
//const int buttonPin = 10;     // the number of the pushbutton pin
const int ledPin = 13;       // the pin that the LED is attached to
unsigned long currentTime;
unsigned long startTime;
unsigned long contractLength = 600000;
unsigned long timeLeft;
//-----------------------------------------------------------------
String inputString = "";         // a String to hold incoming data
String lastSerialVal = "";      //Put the serial value in from 0s to 5min
String currentSerialVal = "";   //Put the current serial value in this variable
String tweet = "";
boolean stringComplete = false;  // whether the string is complete
//-----------------------------------------------------------------
int happened = 0;
int X = 11;
U8X8_SSD1322_NHD_256X64_4W_SW_SPI u8x8(/* clock=*/ 24, /* data=*/ 23, /* cs=*/ 10, /* dc=*/ 9, /* reset=*/ 5);

//-------------------------- Setup --------------------------

void setup()
{
  pinMode(ledPin, OUTPUT);  
  Serial.begin(115200);
  while (!Serial);

  currentTime = 0;
  Serial.print("Start time = ");
  Serial.println(currentTime);

  startTime = millis();

  Serial.print("Finished the setup");
  Serial.println("\n");
  u8x8.begin();
}
//-------------------------- Loop --------------------------

void loop()
{
  currentTime = millis();
  timeLeft = (contractLength - (currentTime - startTime))/1000;
  u8x8.clear();
  u8x8.setFont(u8x8_font_chroma48medium8_r);
  u8x8.setCursor(0, 0);
  u8x8.print(timeLeft);
  delay(1000);
}
```

**Comment by rankinjonathan** [comment]
It all works until I use the io.connect() function on line ~84 for me currently

**Comment by rankinjonathan** [comment]
Ok, late last night I worked out why it wasn't working. Which has unearthed a new problem... Let's see where I get to today!

**Comment by mhamilt** [comment]
Cool, Keep me posted
